services:
  # Our Next.js App Service
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=aristotle
      - DB_NAME=ecommerce
    depends_on:
      - db

  # Our MySQL Database Service
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: aristotle
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
